cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/update/<int:item_id>/', views.update_cart, name='update_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('checkout/gift_cards/', views.gift_card_payment, name='gift_card_payment'),
    path('checkout/cryptocurrency/', views.cryptocurrency_payment, name='cryptocurrency_payment'),
    path('checkout/payment_confirmation/', views.payment_confirmation, name='payment_confirmation'),
]

clothes_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import page_not_found

 
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("accounts/", include("allauth.urls")),
    path("users/", include("users.urls", namespace="users")),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
]

handler404 = page_not_found

users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginUser.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", views.RegisterUser.as_view(), name="register"),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('change-password/', views.UserPasswordChange.as_view(), name="change_password"),
    path('password-reset/', views.CustomPasswordResetView.as_view(
            template_name='users/password_reset.html',
            email_template_name='users/password_reset_email.html',
            success_url=reverse_lazy('users:password_reset_done')
        ),
        name='password_reset'
    ),
    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('oauth/callback/', views.oauth_callback, name='oauth_callback'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    {% block styles %}{% endblock styles %}
    <title>{{ title }}</title>
</head>
<body>
    <div class="page-container">
        <header>
            <div class="container">
                <a href="{% url "main_page" %}">
                    <img src="{% static 'main/img/index/logo_without_back.png' %}" alt="Logo" class="logo">
                </a>
                <nav>
                    <ul>
                        <li><a href="{% url 'new_stuff' %}">New Arrivals</a></li>
                        <li><a href="{% url 'outerwear' %}">Outerwear</a></li>
                        <li><a href="{% url 'accessories' %}">Accessories</a></li>
                        <li><a href="{% url 'sportswear' %}">Sportswear</a></li>
                        <li><a href="{% url 'collections' %}">Collections</a></li>
                        <li><a href="{% url 'client_resources' %}">Client Resources</a></li>
                    </ul>
                </nav>
                <div class="header-widgets">
                    <div class="search-widget">
                        <button id="toggle-search" class="search-icon">
                            <img src="{% static 'main/img/index/search.png' %}" alt="Поиск" />
                        </button>

                        <form id="search-form" method="GET" action="{% url 'search' %}" class="search-form">
                            <input type="text" name="q" placeholder="Search..." value="{{ request.GET.q }}">
                            <button type="submit">Search</button>
                        </form>
                    </div>

                    <a href="{% url 'cart:cart' %}" class="cart-icon"><img src="{% static 'main/img/index/cart.png' %}" alt="Корзина" /></a>
                    <a href="{% url 'users:profile' %}" class="profile-icon"><img src="{% static 'main/img/index/profile1.png' %}" alt="Профиль" /></a>
                </div>
            </div>
        </header>

        <main>
            {% block content %}{% endblock %}
        </main>

        <footer class="footer-banner">
            <div class="footer-content">
                <div class="footer-left">
                    <div class="footer-left1">
                        <h3>STORE</h3>
                        <p>OPEN DAILY:</p>
                        <p>10:00 AM - 9:00 PM</p>
                    </div>
                    <div class="footer-left2">
                        <h3>ADDRESS</h3>
                        <p>8 PRINCES STREET,</p>
                        <p>EDINBURGH,</p>
                        <p>UNITED KINGDOM</p>
                    </div>
                </div>

                <div class="footer-center">
                    <img src="{% static 'main/img/index/logo_without_back.png' %}" alt="Logo" class="footer-logo">
                    <p class="footer-text">© Polaris Aurora 2025. All rights reserved.</p>
                </div>

                <div class="footer-right">
                    <div class="footer-right1">
                        <h3>PHONE</h3>
                        <p>+44 131 496 5555</p>
                    </div>
                    <div class="footer-right2">
                        <h3>EMAIL</h3>
                        <p>info@polarisaurora.com</p>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const toggleSearchButton = document.getElementById("toggle-search");
            const searchForm = document.getElementById("search-form");

            toggleSearchButton.addEventListener("click", (event) => {
                event.stopPropagation();
                if (searchForm.style.display === "block") {
                    searchForm.style.display = "none";
                } else {
                    searchForm.style.display = "block";
                }
            });

            document.addEventListener("click", (event) => {
                if (!searchForm.contains(event.target) && !toggleSearchButton.contains(event.target)) {
                    searchForm.style.display = "none";
                }
            });
        });
    </script>
</body>
</html>